import {
  CELL,
  COLS,
  ROWS,
  PLAYER_ROWS,
  SCORE,
  SCORING as BASE_SCORING,
  EXTRA_LIFE_STEP,
  SPEED,
  TIMERS,
  DENSITY,
  VISUAL,
  POWERUPS as BASE_POWERUPS,
  PLAYER_MECHANICS,
  POWERUP_COLORS as BASE_POWERUP_COLORS,
  REFLECTED_BULLET,
  PSYCHEDELIC,
  COINS
} from './Constants';

export { CELL, COLS, ROWS, PLAYER_ROWS, SCORE, EXTRA_LIFE_STEP, TIMERS, DENSITY, VISUAL, REFLECTED_BULLET, PSYCHEDELIC, COINS };

export const GRID = {
  CELL,
  COLS,
  ROWS,
  PLAYER_ROWS,
} as const;

export const SCORING = {
  ...BASE_SCORING,
  CHAIN_TIMEOUT: SCORE.CHAIN_TIMEOUT
} as const;

export const XQJ37_BLASTER = {
  MAX_PROJECTILES: 1,
  FIRE_RATE: TIMERS.FIRE_COOLDOWN,
  PROJECTILE_SPEED: SPEED.BULLET_PX_PER_SEC,
  MUZZLE_FLASH_TIME: 0.05,
  MACHINE_GUN_RATE: TIMERS.AUTOFIRE_COOLDOWN,
  GUIDED_TURN_RATE: BASE_POWERUPS.GUIDED_SHOT_TURN_RATE,
  TRIPLE_SHOT_ANGLE: BASE_POWERUPS.TRIPLE_SHOT_ANGLE
} as const;

const LARRY_THE_SCOBSTER = {
  SPEED_PX_PER_SEC_X: SPEED.SPIDER_PX_PER_SEC_X,
  SPEED_PX_PER_SEC_Y: SPEED.SPIDER_PX_PER_SEC_Y,
  SCORE_NEAR: SCORE.SPIDER_NEAR,
  SCORE_MED: SCORE.SPIDER_MED,
  SCORE_FAR: SCORE.SPIDER_FAR,
  SPAWN_MIN_TIME: TIMERS.SPAWN_SPIDER_MIN,
  SPAWN_MAX_TIME: TIMERS.SPAWN_SPIDER_MAX
} as const;

const GROUCHO_THE_FLICK = {
  SPEED_PX_PER_SEC_Y: SPEED.FLEA_PX_PER_SEC_Y,
  SCORE: SCORE.FLEA,
  MUSHROOM_DROP_CHANCE: 0.08,
  PLAYER_ROWS_MIN_MUSHES: DENSITY.PLAYER_ROWS_MIN_MUSHES,
  SPAWN_COOLDOWN: TIMERS.SPAWN_FLEA_COOLDOWN
} as const;

const GORDON_THE_GECKO = {
  SPEED_PX_PER_SEC_X: SPEED.SCORPION_PX_PER_SEC_X,
  SCORE: SCORE.SCORPION,
  SPAWN_MIN_TIME: TIMERS.SPAWN_SCORPION_MIN,
  SPAWN_MAX_TIME: TIMERS.SPAWN_SCORPION_MAX
} as const;

const UFO = {
  SPEED_PX_PER_SEC_X: 180,
  SCORE: 1500,
  SPAWN_MIN_TIME: 15,
  SPAWN_MAX_TIME: 30,
  SPAWN_CHANCE: 0.25,
  MUSHROOM_DESTROY_RADIUS: CELL * 1.5
} as const;

export const ENEMIES = {
  PENTIPEDE: {
    SPEED_CELLS_PER_SEC: SPEED.CENTIPEDE_CELLS_PER_SEC,
    SPEED: SPEED.CENTIPEDE_CELLS_PER_SEC,
    DESCENT: 1,
    SEGMENT_POINTS: SCORE.SEGMENT,
    HEAD_POINTS: SCORE.HEAD,
    POISON_SPEED_MULT: 2
  },
  LARRY_THE_SCOBSTER,
  GROUCHO_THE_FLICK,
  GORDON_THE_GECKO,
  UFO,
  // Back-compat aliases used by partially migrated files.
  LARRY: {
    SPEED_X: LARRY_THE_SCOBSTER.SPEED_PX_PER_SEC_X,
    SPEED_Y: LARRY_THE_SCOBSTER.SPEED_PX_PER_SEC_Y,
    POINTS_NEAR: LARRY_THE_SCOBSTER.SCORE_NEAR,
    POINTS_MED: LARRY_THE_SCOBSTER.SCORE_MED,
    POINTS_FAR: LARRY_THE_SCOBSTER.SCORE_FAR,
    SPAWN_MIN: LARRY_THE_SCOBSTER.SPAWN_MIN_TIME,
    SPAWN_MAX: LARRY_THE_SCOBSTER.SPAWN_MAX_TIME
  },
  GROUCHO: {
    SPEED_Y: GROUCHO_THE_FLICK.SPEED_PX_PER_SEC_Y,
    POINTS: GROUCHO_THE_FLICK.SCORE,
    MUSHROOM_DROP_CHANCE: GROUCHO_THE_FLICK.MUSHROOM_DROP_CHANCE,
    SPAWN_THRESHOLD: GROUCHO_THE_FLICK.PLAYER_ROWS_MIN_MUSHES
  },
  GORDON: {
    SPEED_X: GORDON_THE_GECKO.SPEED_PX_PER_SEC_X,
    POINTS: GORDON_THE_GECKO.SCORE,
    POISON_DURATION: 5,
    SPAWN_MIN: GORDON_THE_GECKO.SPAWN_MIN_TIME,
    SPAWN_MAX: GORDON_THE_GECKO.SPAWN_MAX_TIME
  }
} as const;

export const YUMMIES = {
  DURATIONS: {
    MACHINE_GUN: BASE_POWERUPS.MACHINE_GUN_DURATION,
    GUIDED_SHOT: BASE_POWERUPS.GUIDED_SHOT_DURATION,
    TRIPLE_SHOT: BASE_POWERUPS.TRIPLE_SHOT_DURATION,
    SHIELD: BASE_POWERUPS.SHIELD_DURATION,
    SPEED_BOOST: BASE_POWERUPS.SPEED_BOOST_DURATION,
    GHOST_MODE: BASE_POWERUPS.GHOST_MODE_DURATION,
    NUKE: BASE_POWERUPS.NUKE_DURATION
  },
  VISUALS: {
    FADE_TIME: BASE_POWERUPS.FADE_TIME,
    FLOAT_AMPLITUDE: BASE_POWERUPS.FLOAT_AMPLITUDE,
    FLOAT_SPEED: BASE_POWERUPS.FLOAT_SPEED,
    SHIELD_FLASH_RATE: BASE_POWERUPS.SHIELD_FLASH_RATE
  },
  SPAWN: {
    CHANCE: BASE_POWERUPS.SPAWN_CHANCE,
    MAX_ACTIVE: BASE_POWERUPS.MAX_ACTIVE,
    MIN_SPACING: 3
  },
  TYPES: BASE_POWERUPS.TYPES,
  COLORS: {
    MACHINE_GUN: BASE_POWERUP_COLORS.machine_gun,
    GUIDED: BASE_POWERUP_COLORS.guided,
    TRIPLE: BASE_POWERUP_COLORS.triple,
    SHIELD: BASE_POWERUP_COLORS.shield,
    SPEED: BASE_POWERUP_COLORS.speed,
    GHOST: BASE_POWERUP_COLORS.ghost,
    NUKE: BASE_POWERUP_COLORS.nuke
  }
} as const;

export const POWERUPS = {
  ...BASE_POWERUPS,
  AUTOFIRE_DURATION: BASE_POWERUPS.MACHINE_GUN_DURATION,
  SPREAD_SHOT_DURATION: BASE_POWERUPS.TRIPLE_SHOT_DURATION,
  RAPID_FIRE_DURATION: BASE_POWERUPS.MACHINE_GUN_DURATION,
  ENERGY_SHIELD_DURATION: BASE_POWERUPS.SHIELD_DURATION,
  WARP_SPEED_DURATION: BASE_POWERUPS.SPEED_BOOST_DURATION,
  PHASE_SHIFT_DURATION: BASE_POWERUPS.GHOST_MODE_DURATION,
  MEGA_BLAST_DURATION: BASE_POWERUPS.NUKE_DURATION,
  SPREAD_SHOT_ANGLE: BASE_POWERUPS.TRIPLE_SHOT_ANGLE,
  RAPID_FIRE_MULTIPLIER: 2.5,
  SHIELD_FLASH_RATE: BASE_POWERUPS.SHIELD_FLASH_RATE,
  WARP_SPEED_MULTIPLIER: BASE_POWERUPS.SPEED_BOOST_MULT,
  PHASE_SHIFT_COOLDOWN: 1.0,
  MEGA_BLAST_RADIUS: BASE_POWERUPS.NUKE_RADIUS
} as const;

export const POWERUP_COLORS = {
  autofire: BASE_POWERUP_COLORS.machine_gun,
  spread: BASE_POWERUP_COLORS.triple,
  rapid: '#40c4ff',
  shield: BASE_POWERUP_COLORS.shield,
  warp: BASE_POWERUP_COLORS.speed,
  phase: BASE_POWERUP_COLORS.ghost,
  mega: BASE_POWERUP_COLORS.nuke,
  machine_gun: BASE_POWERUP_COLORS.machine_gun,
  guided: BASE_POWERUP_COLORS.guided,
  triple: BASE_POWERUP_COLORS.triple,
  speed: BASE_POWERUP_COLORS.speed,
  ghost: BASE_POWERUP_COLORS.ghost,
  nuke: BASE_POWERUP_COLORS.nuke
} as const;

export const PLAYER = {
  MOVEMENT: {
    BASE_SPEED: SPEED.PLAYER_PX_PER_SEC,
    ACCEL: SPEED.PLAYER_ACCEL,
    DECEL: SPEED.PLAYER_DECEL,
    VERTICAL_MULT: SPEED.PLAYER_VERTICAL_MULT,
    MOMENTUM_DECAY: PLAYER_MECHANICS.MOMENTUM_DECAY,
    MAX_VELOCITY: PLAYER_MECHANICS.MAX_VELOCITY
  },
  SIZE: {
    WIDTH: GRID.CELL * 1.42,
    HEIGHT: GRID.CELL * 1.08
  },
  ABILITIES: {
    MAX_ENERGY: PLAYER_MECHANICS.MAX_ENERGY,
    ENERGY_REGEN: PLAYER_MECHANICS.ENERGY_REGEN,
    DASH_SPEED: PLAYER_MECHANICS.DASH_SPEED,
    DASH_DURATION: PLAYER_MECHANICS.DASH_DURATION,
    DASH_COOLDOWN: PLAYER_MECHANICS.DASH_COOLDOWN,
    DASH_INVULN: PLAYER_MECHANICS.DASH_INVULN
  }
} as const;

export const MUSHROOMS = {
  SIZE: GRID.CELL * 0.8,
  MAX_HP: 4,
  POINTS: {
    HIT: SCORE.MUSHROOM_HIT,
    CLEAR: SCORE.MUSHROOM_CLEAR_BONUS,
    FIELD_BONUS: SCORE.MUSHROOM_FIELD_BONUS
  },
  POISON: {
    DURATION: 5,
    SPREAD_CHANCE: 0.2
  }
} as const;

export const DEBUG = {
  SHOW_HITBOXES: false,
  SHOW_PATHS: false,
  SHOW_GRID: false,
  SHOW_FPS: false,
  INVINCIBLE: false,
  INFINITE_YUMMIES: false
} as const;
